# Generated by Django 2.2.3 on 2019-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_type',
            name='type_img',
            field=models.ImageField(upload_to='fresh/images/', verbose_name='商品图片'),
        ),
    ]
